version: '3.8'

services:
  # Application container
  php:
    build: .
    restart: unless-stopped
    volumes:
      - ./:/server/http
    ports:
      - "8080:80"
      #- "443:443"
    links:
      - mysql
    environment:
      DEBUG: 'true'

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: recipes_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
